### ISSUE TITLE
Finally found a wolf and it crashed.

### ISSUE THREAD

**Issue by frakier** [CenturionFox/wolfarmor#21]
Looked at the other crashes and they seemed to be different so posting.
this one starts off as 
java.lang.ClassCastException: java.lang.Byte cannot be cast to com.google.common.base.Optional
forge 2281
wolfarmor-1.4.1.0.jar

[crash-2017-09-15_18.07.06-client.txt](https://github.com/CenturionFox/wolfarmor/files/1307841/crash-2017-09-15_18.07.06-client.txt)

**Comment by CenturionFox** [comment]
ah, so this was always a problem then.  See #13, #34, #38.  Merged into #41
