### ISSUE TITLE
Wolf armor crashing on 1.12

### ISSUE THREAD

**Issue by Raycoms** [CenturionFox/wolfarmor#34]
Wolf armor is crashing on our 1.12 server with sponge casting a boolean to an itemStack.

It seems to happen when a player hovers a bone over a wolf.

> [12:50:12] [main/ERROR]: Couldn't render entity
> java.lang.ClassCastException: java.lang.Boolean cannot be cast to net.minecraft.item.ItemStack
> 	at com.attributestudios.wolfarmor.common.capabilities.CapabilityWolfArmor$Instance.getArmorItemStack(CapabilityWolfArmor.java:274) ~[CapabilityWolfArmor$Instance.class:?]
> 	at com.attributestudios.wolfarmor.client.renderer.entity.layer.LayerWolfArmor.doRenderLayer(LayerWolfArmor.java:93) ~[LayerWolfArmor.class:?]
> 	at com.attributestudios.wolfarmor.client.renderer.entity.layer.LayerWolfArmor.func_177141_a(LayerWolfArmor.java:28) ~[LayerWolfArmor.class:?]
> 	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:439) ~[caa.class:?]
> 	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:186) [caa.class:?]
> 	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) [caf.class:?]
> 	at net.minecraft.client.renderer.entity.RenderWolf.func_76986_a(SourceFile:33) [cbm.class:?]
> 	at net.minecraft.client.renderer.entity.RenderWolf.func_76986_a(SourceFile:9) [cbm.class:?]
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) [bzf.class:?]
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368) [bzf.class:?]
> 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628) [buy.class:?]
> 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345) [buq.class:?]
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) [bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
> 	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by CenturionFox** [comment]
Ugh, looks like it's related to #38.  I'll have to figure out how capabilities sync rather than just using the ported functionality from the old entity override.

**Comment by CenturionFox** [comment]
Issue merged with related issues #13, #38, see #41
