### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by NightKosh** [CenturionFox/wolfarmor#35]
Hello. I need few changes in your API to improve compatibility with Sophisticated wolves mod.
1) Could you please add a method to set chest items to IWolfArmorCapability
2) It is required to move CapabilityWolfArmor.WOLF_ARMOR_CAPABILITY field somewhere to your API.

P.S. could you please explain how you render wolf armor and chest? unfortunately this objects doesn't rendered at sophisticated wolves.

**Comment by CenturionFox** [comment]
For rendering the wolf armor and backpacks I add render layers to the default model.  There was also an attempt made to add those layers to the sophisticated wolf renderer, but I probably need to update it.  I may be able to add a method of obtaining the custom render layers from the API.

**Comment by CenturionFox** [comment]
@NightKosh I've got a temporary render fix in now, but to do it "right" I think you'll have to add the render layers yourself via com.attributestudios.wolfarmor.api.client.RenderLayerFactory
Thanks!

**Comment by NightKosh** [comment]
Thank you a lot!

**Comment by Braffolk** [comment]
Are you working on the "It is required to move CapabilityWolfArmor.WOLF_ARMOR_CAPABILITY field somewhere to your API." issue too? The problem appears once you try to turn the default wolf into a sophisticated wolf by using an item on them to do that.

Here's an example error log: https://paste.dimdev.org/decixuzipo.txt

**Comment by NightKosh** [comment]
@Braffolk it will be fixed in sophisticated wolves

**Comment by NightKosh** [comment]
@Braffolk here is a fixed version https://minecraft.curseforge.com/projects/sophisticated-wolves/files/2567412
