### ISSUE TITLE
Server Crash [Ticking entity]: getMoonPhase unavailable on server side

### ISSUE THREAD

**Issue by vertex101** [CenturionFox/wolfarmor#37]
https://paste.ee/p/kDdVe

**Comment by Midnex** [comment]
Would love to see this fixed. Could post 30+ logs of this issue using wolfarmor-1.12.2-2.1.0.24-RELEASE
https://pastebin.com/qncLUn4B case the more logs help.

**Comment by ExcitedName** [comment]
@vertex101 if you set your config to enableHowlingUntamedWolves=false it should prevent the crash. It worked for me. Did it resolve the problem for you @Midnex?

**Comment by Midnex** [comment]
Yes it did
