### ISSUE TITLE
Log error with a prominent mention of Wolf Armor

### ISSUE THREAD

**Issue by NotAVerb** [CenturionFox/wolfarmor#38]
It's something about a duplicate ID. Some sort of mod conflict then. I'm not actually sure what is breaking in game, but Wolf Armor is the first mod mentioned by name in the log.

https://gist.github.com/NotAVerb/f1591ae0ac2a03825a9f46ff29ef1ff6
MC 1.12.2
Forge 2607
Wolf Armor 2.1.0.24

**Comment by CenturionFox** [comment]
Issue merged with related issues #13, #34, see #41
