### ISSUE TITLE
Crash with Bloodmoon and wolfarmor

### ISSUE THREAD

**Issue by vpontin** [CenturionFox/wolfarmor#39]
When enabling Wolfs howling on full moon + bloodmoons happening every full moon at the first bloodmoon in the world i got a crash (first gist). The second gist is when i reattempt to open the world.

https://gist.github.com/vpontin/bc493c6d86d3984a1a1e3e691f25a3fd

Since i dont know what mod is responsible i will drop the same issue here an there.

https://github.com/lumien231/Bloodmoon/issues/28

**Comment by CenturionFox** [comment]
hey, a getMoonPhase issue.  This is actually also my fault, and it's even the same problem! See #37

**Comment by vpontin** [comment]
Strange, @lumien231 also claimed it was their fault, but anyway thanks for the reply! Very useful mod!
