### ISSUE TITLE
Sound Bug with Tschipp/CarryOn

### ISSUE THREAD

**Issue by CenturionFox** [CenturionFox/wolfarmor#42]
From @Tschipp [CarryOn (#106)](http://github.com/Tschipp/CarryOn/issues/106):  Sound events play when the NBT data is deserialized; call to onInventoryChanged.

**Comment by CenturionFox** [comment]
oh weird.
Didn't yet manage to fix the sound issue, but now armor renders properly on the carried wolf, so it's a start...?

**Comment by CenturionFox** [comment]
Managed to fix it!

**Comment by Tschipp** [comment]
Great!
