### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by BuilderDan** [CenturionFox/wolfarmor#43]
**Issue Description**
Was walking through the world minding my own business when suddenly my server crashed.

**Reproduction Steps**
Walk around till you load a chunk with a wolf I am assuming?

**Expected Behavior**
For the server to not crash.

**Version Information:**
 - OS: Windows 10
 - Java: java 8
 - Minecraft Version: 1.12.2
 - Forge: forge-1.12.2-14.23.3.2675-universal.jar
 - Mod Version: wolfarmor-1.12.2-2.1.0.24-RELEASE.jar

**Additional Context**
Crash: https://pastebin.com/Z8xmJnyd

**Comment by BuilderDan** [comment]
The server refuses to start even after the world has been deleted, the same crash occurs each time...

**Comment by CenturionFox** [comment]
Disable howling wolves for now, just checked in a change to fix. see #37

**Comment by CenturionFox** [comment]
And now you can download patch 26 which implements the fix.  Hope this solves your issue, and thanks for the report!
