### ISSUE TITLE
Winter Wolf Entity from Twilight Forest breaks and won't spawn

### ISSUE THREAD

**Issue by Ghostrider231** [CenturionFox/wolfarmor#44]
### **Issue Description**
**While this mod and twilight forest are both installed**. It seems that Winter Wolves are broken when they attempt to spawn.

If I try to find these broken Winter Wolves spawning naturally in the twilight forest's Snowy Forest Biome, the game instead may not even spawn them. Or even worse, crash the game. Since it's trying to spawn an invalid/broken entity. (I can't find the crash log for that one since it's buried deep into my other debugged crashes)

I've tried submitting a issue report to the twilight forest issue tracker, but got no response to them: https://github.com/TeamTwilight/twilightforest/issues/455 

### **Relevant Mods**
Twilight Forest - MC 1.12.2 - 3.7.424 (latest version)

## 1 - Spawning Winter Wolf via spawn eggs
1. Be in Creative mode.
2. Get a Winter Wolf egg from the creative menu.
3. Use the Winter Wolf spawn egg.
4. It won't spawn anything. (error: https://pastebin.com/JzjxRVD2)

## 2 - Now, this second part CAN be skipped, since the first one already explains the issue anyways. (So, you can do this if you want, but I suggest you don't, since this one takes a while)
1. Be in Creative mode. (If you want)
2. Enter the twilight forest.
3. Find a Snowy Forest Biome.
4. Winter Wolves were either likely won't spawn or crash the game.

### **Expected Behavior**
I've expected the Winter Wolf from twilight forest to spawn normally and behave normally with this installed.

### **Actual Behavior**
Winter Wolves won't spawn via spawn eggs or natural. And instead give out a "**Duplicate id value for 18**" The same error I've posted above: https://pastebin.com/JzjxRVD2

### **Screenshots / Videos**
N/A

### **Version Information:**
 - Java: 1.8.0_171 64bit
 - Minecraft Version: 1.12.2
 - Mod Version: 1.12.2-2.1.0.26 (Latest version)

### **Additional Context**
N/A

**Comment by CenturionFox** [comment]
Looks like the same issue with the capability data manager as #41 and the linked items therein.  Thanks for the report!
