### ISSUE TITLE
Wolf armor resets when reloading the world

### ISSUE THREAD

**Issue by Ghostrider231** [CenturionFox/wolfarmor#45]
### **Issue Description**
When equipping your wolves with armor then reloading the world seems to have reset their armor slot, which completely erases their armor entirely. Requiring you to reequip them with new armor if you happen to touch their armor slot.

### **Reproduction Steps**
1. Have a Tamed Wolf.
2. Sneak-Right click the Wolf.
3. Equip it with any armor tier level.
4. Save and quit the world.
5. Reenter the world.
6. Sneak-Right click the wolf again.
7. **The Armor slot should be a blank, and clicking it removes the armor. (Instead of taking it off)**

### **Expected Behavior**
Reloading the world with the wolves having armor equipped intact.

### **Screenshots / Videos**
Wolf has armor:

![2018-05-29_20 35 34](https://user-images.githubusercontent.com/36087678/40697651-2394057a-6380-11e8-8d04-c7774c783442.png)

=======================

After reloading the world:

![2018-05-29_20 35 55](https://user-images.githubusercontent.com/36087678/40697637-160ec7d2-6380-11e8-84d6-cb850a642c43.png)

### **Version Information:**
 - Minecraft Version: 1.12.2
 - Mod Version: 1.12.2-2.2.3.1797-universal

### **Additional Context**
Don't worry about the other stuff involved, those mods have nothing to do with this. Because I've tested this with only this mod installed.

**Comment by CenturionFox** [comment]
Was this in a server or in a local world?
