### ISSUE TITLE
Crash with sophisticated wolves (WAILA issue)

### ISSUE THREAD

**Issue by Tyrant0x1** [CenturionFox/wolfarmor#7]
With the 1.4.1.0 alpha version and Sophisticated Wolves (the latest, version 3.6.4) installed, i get a very occasional issue where a wolf appears as only its shadow (no wolf rendered). Looking at the wolf causes the game to crash.
Here is the crash log: 
[crash-2017-02-02_18.27.58-client.txt.zip](https://github.com/CenturionFox/wolfarmor/files/749449/crash-2017-02-02_18.27.58-client.txt.zip)

**Comment by CenturionFox** [comment]
Hmm... this looks like it could be a Waila incompatibility.  I'll look into it.

**Comment by CenturionFox** [comment]
Merged with #13, #21, #34, #38 in #41
